exports.adminNotificationTemplate = (contact) => {
  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 20px; border: 1px solid #ddd; border-radius: 10px;">
      <h2 style="color: #333;">📩 New Contact Submission</h2>
      <p><strong>Name:</strong> ${contact?.name}</p>
      <p><strong>Email:</strong> ${contact?.email}</p>
      <p><strong>Message:</strong></p>
      <blockquote style="background: #f9f9f9; padding: 10px; border-left: 4px solid #007bff;">
        ${contact?.message}
      </blockquote>
      <hr>
      <p style="color: #888; font-size: 14px;">This email was automatically generated by your website.</p>
    </div>
  `;
};
